services:

  postgresql:
    restart: always
    image: postgres:14
    command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr, csvlog"]
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./initPostgres/create.sql:/docker-entrypoint-initdb.d/create.sql
      #- ./postgreSQL/set.sql:/docker-entrypoint-initdb.d/set.sql
    ports:
      - 5444:5432

  app:
    build: .
    ports:
      - 8085:8080
    depends_on:
      - postgresql
    command: ["wait-for-it.sh", "postgresql:5432", "--", "/app/bin"]